server:
  port: 9089

spring:
  application:
    name: service-auth

  redis:
    host: 118.25.14.73
    database: 0
    password: ReDis@.1*1PW1
    port: 6379

  datasource:
    url: jdbc:mysql://192.168.1.83:3306/heweiTest1?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      # 向服务中心注册自己 (无密码注册)
      #defaultZone: http://localhost:8761/eureka/

      #使用密码注册
      defaultZone: http://hwei:hewei@localhost:8761/eureka/

      instance:
        #使用真实ip注册
        prefer-ip-address: true
