server:
  port: 9089

spring:
  application:
    name: service-auth

  redis:
    host: 118.25.14.73
    database: 0
    password: ReDis@.1*1PW1
    port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

