server:
  port: 8081
  #port: 8082
  #port: 8083
spring:
  application:
    name: eureka-service-demo1

eureka:
  client:
    serviceUrl:
      # 向服务中心注册自己 (无密码注册)
      #defaultZone: http://localhost:8761/eureka/

      #使用密码注册
      defaultZone: http://hwei:hewei@localhost:8761/eureka/


  instance:
    #使用真实ip注册
    prefer-ip-address: true

    # 每隔10s发送一次心跳
    lease-renewal-interval-in-seconds: 10
    # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 30