spring:
  application:
    name: config-server-demo1

  cloud:
    config:
      server:
        git:
          # git仓库地址
          uri: https://gitlab.com/hweeeeeei/cloud-demo-1.git

          # 仓库路径
          searchPaths: SpringcloudConfig/respo
          username: hwei1233@163.com
          password: aiweige233..0
      # 分支
      label: master

server:
  port: 8088