spring:
  application:
    name: config-server-demo1

  cloud:
    config:
      server:
        git:
          # git仓库地址
          uri: https://gitlab.com/hweeeeeei/cloud-demo-1.git

          # 仓库路径
          searchPaths: SpringcloudConfig/respo
          username: hwei1233@163.com
          password: aiweige233..0
      # 分支
      label: master

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    #使用真实ip注册
    prefer-ip-address: true

    # 每隔10s发送一次心跳
    lease-renewal-interval-in-seconds: 10
    # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 30