server:
  port: 8085

spring:
  application:
    name: feign-demo1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

    #eureka client刷新本地缓存时间, 默认30s
    registry-fetch-interval-seconds: 5

  instance:
    #使用真实ip注册
    prefer-ip-address: true
    # 每隔10s发送一次心跳
    lease-renewal-interval-in-seconds: 10
    # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 30