server:
  port: 9189

spring:
  application:
    name: service-hi

  redis:
    host: 118.25.14.73
    database: 0
    password: ReDis@.1*1PW1
    port: 6379

  datasource:
    url: jdbc:mysql://118.25.14.73:3306/hweT1?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: mysql.*2018/

    #url: jdbc:mysql://192.168.1.83:3306/heweiTest1?useUnicode=true&useSSL=false&characterEncoding=utf8
    #    username: root
    #    password: 123456

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      # 向服务中心注册自己 (无密码注册)
      #defaultZone: http://localhost:8761/eureka/

      #使用密码注册
      defaultZone: http://hwei:hewei@localhost:8761/eureka/

      instance:
        #使用真实ip注册
        prefer-ip-address: true
security:
  oauth2:
    resource:
      jwt:
        #提供公有密匙的端点
        key-uri: http://localhost:9089/oauth/token_key


    #clientId、client-secret等信息要和service-auth中的配置对应。
    # 如果运行报错, 需要在数据库表中添加此client信息
    client:
      client-id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:9089/oauth/token
      grant-type: password
      scope: server
      user-authorization-uri: http://localhost:9089/oauth/authorize
logging:
  level:
    root: debug
