spring:
  application:
    name: service-zuul-demo1

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    #使用真实ip注册
    prefer-ip-address: true

    # 每隔10s发送一次心跳
    lease-renewal-interval-in-seconds: 10
    # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 30

zuul:
  routes:

    #/api-a/ 开头的请求都转发给feign-demo1服务；
    api-a:
      path: /api-a/**
      serviceId: feign-demo1

    #/api-b/ 开头的请求都转发给ribbon-demo1服务；
    api-b:
      path: /api-b/**
      serviceId: ribbon-demo1